version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/graphql"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/collector"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/worker"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/stack"
    schedule:
      interval: "weekly"
