version = 1

[[analyzers]]
name = "javascript"
enabled = true

[analyzers.meta]
plugins = ["react"]
environment = ["nodejs", "browser"]
module_system = "es-modules"
dependency_file_paths = ["web/package.json"]

[[analyzers]]
name = "go"
enabled = true

[analyzers.meta]
import_root = ["github.com/kazimanzurrashid/aws-scheduler-go/graphql", "github.com/kazimanzurrashid/aws-scheduler-go/collector", "github.com/kazimanzurrashid/aws-scheduler-go/worker"]
