version = 1

test_patterns = [
  "collector/**/*_test.go",
  "graphql/**/*_test.go",
  "worker/**/*_test.go"
]

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]
  environment = ["nodejs","browser"]
  module_system = "es-modules"
  dependency_file_paths = ["web/package.json"]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/kazimanzurrashid/go"
  dependencies_vendored = false
