name: collector
on:
  push:
    branches:
      - main
    paths:
      - 'collector/**/**'
      - '.github/workflows/collector.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'collector/**/**'
      - '.github/workflows/collector.yml'
jobs:
  collector:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Go setup
        uses: actions/setup-go@v5
        with:
          go-version: 1.19.x

      - name: Pack
        run: |
          cd collector
          go get -t -d ./...
          go test ./...
          mkdir -p dist
          CGO_ENABLED=0 GOOS=linux go build -o dist/main
          cd dist
          zip -r -9 scheduler-collector-v1.zip ./*

      - name: Update
        if: ${{ github.event_name == 'push' && github.ref_name == 'main' && env.AWS_REGION != '' }}
        uses: kazimanzurrashid/aws-lambda-update-action@v2.0.2
        with:
          zip-file: ./collector/dist/scheduler-collector-v1.zip
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
