name: graphql
on:
  push:
    branches:
      - main
    paths:
      - 'graphql/**/**'
      - '.github/workflows/graphql.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'graphql/**/**'
      - '.github/workflows/graphql.yml'
jobs:
  graphql:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Go setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: Pack
        run: |
          cd graphql
          go get -t -d ./...
          go test ./...
          mkdir -p dist
          CGO_ENABLED=0 GOOS=linux go build -o dist/main
          cp pages dist/ -r
          cd dist
          zip -r -9 scheduler-graphql-v1.zip ./*

      - name: Update
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && env.AWS_REGION != '' }}
        uses: kazimanzurrashid/aws-lambda-update-action@v1
        with:
          zip-file: ./graphql/dist/scheduler-graphql-v1.zip
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
